---
global-variables:
  acp-docker-image: &acp-docker-image 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind:latest

kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build_docker_image
  pull: if-not-exists
  image: *acp-docker-image
  commands:
    - /usr/local/bin/wait
    - docker build --tag dq-packer-ansible:b-$${DRONE_BUILD_NUMBER} .
  when:
    event:
    - push

- name: push_image_to_quay
  pull: if-not-exists
  image: *acp-docker-image
  commands:
    - docker login --username=$${DOCKER_USERNAME} --password=$${DOCKER_PASSWORD} quay.io
    - docker tag dq-packer-ansible:b-$${DRONE_BUILD_NUMBER} quay.io/ukhomeofficedigital/dq-packer-ansible:b-$${DRONE_BUILD_NUMBER}
    - docker push quay.io/ukhomeofficedigital/dq-packer-ansible:b-$${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: trivy_scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:master
  commands:
  - trivy image --ignore-unfixed --exit-code 0 --no-progress quay.io/ukhomeofficedigital/dq-packer-ansible:${DRONE_BUILD_NUMBER}
  when:
    branch:
      exclude:
        - master
    event:
      - push


- name: push_master_image_to_quay
  pull: if-not-exists
  image: *acp-docker-image
  commands:
    - docker login --username=$${DOCKER_USERNAME} --password=$${DOCKER_PASSWORD} quay.io
    - docker tag dq-packer-ansible:b-$${DRONE_BUILD_NUMBER} quay.io/ukhomeofficedigital/dq-packer-ansible:b-$${DRONE_BUILD_NUMBER}
    - docker push quay.io/ukhomeofficedigital/dq-packer-ansible:b-$${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  when:
    branch:
      - master
    event:
    - push

- name: trivy_scan_master
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:master
  commands:
  - trivy image --ignore-unfixed --exit-code 0 --no-progress quay.io/ukhomeofficedigital/dq-packer-ansible:b-${DRONE_BUILD_NUMBER}
  when:
    branch:
      - master
    event:
      - push


- name: promote_master
  pull: if-not-exists
  image: *acp-docker-image
  commands:
    - docker login --username=$${DOCKER_USERNAME} --password=$${DOCKER_PASSWORD} quay.io
    - docker tag dq-packer-ansible:b-$${DRONE_BUILD_NUMBER} quay.io/ukhomeofficedigital/dq-packer-ansible:latest
    - docker push quay.io/ukhomeofficedigital/dq-packer-ansible:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  when:
    branch:
      - master
    event:
      - promote
    target:
      - production

services:
- name: docker
  image: *acp-docker-image
